### PR TITLE
Bump runtime to 42

### PR DESCRIPTION
**Pull request by bbhtt**
Hey, @SubhadeepJasu, please review when you have time, thanks!

### CODE REVIEW

**Comment by SubhadeepJasu** [comment]
Sure. I'll be busy for today and the next day. I'll test it out after that if you don't mind.

**Comment by bbhtt** [comment]
> Sure. I'll be busy for today and the next day. I'll test it out after that if you don't mind.

No worries, please take your time :)

**Comment by SubhadeepJasu** [comment]
bot, build com.github.subhadeepjasu.pebbles. Building because the previous artifact seems to be unavailable.

**Comment by SubhadeepJasu** [comment]
Typo

bot, build com.github.subhadeepjasu.pebbles

**Comment by SubhadeepJasu** [comment]
Not sure what's going on 
image

**Comment by bbhtt** [comment]
Maybe it is installed in --user and you're trying to install the test flatpak systemwide? 103782 seems to work fine here.

**Comment by SubhadeepJasu** [comment]
yeah it works! Thanks!

**Pull request merged**
