### PR TITLE
Update runtime to 23.08

### PR DESCRIPTION
**Pull request by ghost**
GNOME runtime version 44 has reached EOL.

### CODE REVIEW

**Comment by ghost** [comment]
@SubhadeepJasu and @bbhtt Ready for review.

**Comment by SubhadeepJasu** [comment]
Looks good! What's going on with the icon patch?

**Comment by ghost** [comment]
> Looks good! What's going on with the icon patch?

To pass flatpak linter's  non-png-icon-in-hicolor-size-folder error

```
{
    "errors": [
        "non-png-icon-in-hicolor-size-folder"
    ],
    "info": [
        "non-png-icon-in-hicolor-size-folder: ['/tmp/tmp9ejj3ikz/icons/hicolor/24x24/apps/com.github.subhadeepjasu.pebbles.svg', '/tmp/tmp9ejj3ikz/icons/hicolor/64x64/apps/com.github.subhadeepjasu.pebbles.svg', '/tmp/tmp9ejj3ikz/icons/hicolor/32x32@2/apps/com.github.subhadeepjasu.pebbles.svg', '/tmp/tmp9ejj3ikz/icons/hicolor/48x48@2/apps/com.github.subhadeepjasu.pebbles.svg', '/tmp/tmp9ejj3ikz/icons/hicolor/16x16@2/apps/com.github.subhadeepjasu.pebbles.svg', '/tmp/tmp9ejj3ikz/icons/hicolor/128x128/apps/com.github.subhadeepjasu.pebbles.svg', '/tmp/tmp9ejj3ikz/icons/hicolor/128x128@2/apps/com.github.subhadeepjasu.pebbles.svg', '/tmp/tmp9ejj3ikz/icons/hicolor/32x32/apps/com.github.subhadeepjasu.pebbles.svg', '/tmp/tmp9ejj3ikz/icons/hicolor/24x24@2/apps/com.github.subhadeepjasu.pebbles.svg', '/tmp/tmp9ejj3ikz/icons/hicolor/16x16/apps/com.github.subhadeepjasu.pebbles.svg', '/tmp/tmp9ejj3ikz/icons/hicolor/48x48/apps/com.github.subhadeepjasu.pebbles.svg', '/tmp/tmp9ejj3ikz/icons/hicolor/64x64@2/apps/com.github.subhadeepjasu.pebbles.svg']"
    ],
    "message": "Please consult the documentation at https://docs.flathub.org/docs/for-app-authors/linter"
}
```

**Comment by ghost** [comment]
For more information

> ### non-png-icon-in-hicolor-size-folder
> 
> An icon file with an extension other than .png was installed to $FLATPAK_DEST/share/icons/hicolor/$size/apps (builddir/share/icons/hicolor/$size/apps for the local build directory).
> 
> The sized folders are only reserved for PNG icons.

Source: https://docs.flathub.org/docs/for-app-authors/linter/#non-png-icon-in-hicolor-size-folder

**Pull request merged**
